# Generated by Django 3.0.5 on 2020-05-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheer',
            name='created_date',
            field=models.DateTimeField(default='auto_now_add=True'),
        ),
    ]
