# Generated by Django 3.0.5 on 2020-05-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0003_remove_cheer_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheer',
            name='created_date',
            field=models.DateTimeField(default=''),
        ),
    ]
