# Generated by Django 3.0.5 on 2020-05-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0004_cheer_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheer',
            name='created_date',
        ),
        migrations.AddField(
            model_name='cheer',
            name='pub_date',
            field=models.DateTimeField(default='date published'),
        ),
    ]
