# Generated by Django 3.0.5 on 2020-05-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0005_auto_20200513_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheer',
            name='pub_date',
        ),
    ]
