# Generated by Django 3.0.5 on 2020-05-12 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_image_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='photo',
        ),
    ]
